#!/usr/bin/env bash
#?
# bkground - Sets the system's background
#
# Usage: bkground
#
# Behavior:
#	Sets the desktop background image using feh to the image specified by 
#	the $bg_dir and $bg_file variables in the script.
#?

# Help option
if [[ "$1" =~ ^(--help|-h)$ ]]; then
	show-help "$0"
	exit 1
fi

# Config

# Directory backgrounds are located in. The path must end in a forward slash.
bg_dir="$HOME/Documents/pictures/"

# File in directory to set as background
bg_file="skyline.png"

# Set background
feh --bg-scale "${bg_dir}${bg_file}"
