#!/usr/bin/env bash
#?
# bkground - Sets the system's background
#
# Usage: bkground
#?

# Config

# Directory backgrounds are located in. The path must end in a forward slash.
bg_dir="$HOME/Documents/pictures/"

# File in directory to set as background
bg_file="winter.png"

# Set background
feh --bg-scale "${bg_dir}${bg_file}"
