#!/usr/bin/env bash
#?
# edit - Edit file with $EDITOR
#
# USAGE
#
#    edit ...
#
# OPTIONS / ARGUMENTS
#
#    Passes all options / arguments to $EDITOR program.
#
# BEHAVIOR
#
#    Run program specified by $EDITOR.
#
#    $EDITOR must be set.
#
#?

if [ -z "$EDITOR" ]; then
    echo "Error: EDITOR environment variable must be set" >&2
    exit 1
fi

exec "$EDITOR" $@
