#!/usr/bin/env bash
#?
# FTerm - Opens up a terminal as a floating window
#
# USAGE
#	fterm [OPTIONS]
#
# OPTIONS
#	--help,-h    Display help text
#
# BEHAVIOR
#	Opens a terminal as a floating window with BSPWM.
#?

# Help argument
if [[ "$1" =~ ^(--help|-h)$ ]]; then
	show-help "$0"
	exit 1
fi

# Open
bspc rule -a \* -o state=floating && $TERMINAL && bspc rule -r \* -o state=floating

