#!/usr/bin/env bash
#?
# NVim Swap - Cleans the nvim swap directory.
#
# USAGE
#	nvim-swap [OPTIONS]
#
# OPTIONS
#	--help,-h    Display help text
#
# BEHAVIOR
#	Clears all swap files from the NVim swap directory
#?

# Help argument
if [[ "$1" =~ ^(--help|-h)$ ]]; then
	show-help "$0"
	exit 1
fi

# Clean
echo "Cleaning nvim swap directory"
rm $HOME/.local/share/nvim/swap/*.swp || echo "No swap files"
