#!/usr/bin/env bash
#?
# Show Help - Prints the help documentation located in the top comments of a 
#             script. 
#
# USAGE
#	show-help [OPTIONS] FILE
#
# ARGUMENTS
# 	1. FILE (string): Path of file to print help text of
#
# OPTIONS
#	--help,-h       Display help text
#
# BEHAVIOR
# 	Prints the text between the help tags in the top comment of the file.
#
#	More specifically the text between the two "#?" help tags. 
#	These help tags designate exactly which text should be printed.
#?

# Options
# While more than one arg, process option and shift
while [ ! -z "$1" ]; do
	case "$1" in
		--help|-h)
			show-help "$0"
			exit 1
			;;
		*)
			filePath="$1"
			;;
	esac

	shift
done

# Check file path provided
if [ -z "$filePath" ]; then
	echo "Error: File argument must be provided" >&2
	exit 1
fi

# If doesn't exist
if [[ ! -f "$filePath" ]]; then
	echo "Provided file \"$filePath\" does not exist" >&2
	exit 1
fi

# Print text between help tags:
# 	1. Echo file contents
# 	2. Only show text between help tags
# 	3. Remove lines containing help tags
# 	4. Remove beginning comment hash
cat "$filePath" | \
	sed -n '/^#?/,/^#?/p' | \
	grep -v '^#?' | \
	sed 's/^#[ ]\?//g' 
