#!/usr/bin/env bash
#?
# Touchx - Creates a file with execution privileges
# 
# USAGE
#	touchx FILE [OPTIONS]
#
# ARGUMENTS
#	1. FILE (String): File to create
#
# OPTIONS
#	--help,-h    Display help text
#
# BEHAVIOR
#	Creates a file with execution permissions.
#?

# Arguments
file="$1"
if [ -z "$file" ]; then
	echo "Error: file argument must be provided" >&2
	show-help "$0"
	exit 1
elif [[ "$file" =~ ^(--help|-h)$ ]]; then
	show-help "$0"
	exit 1
fi

# Create file
touch "$file"
chmod +x "$file"
