#!/usr/bin/env bash
#?
# wifi - Shortcut to connect to wifi networks
#
# USAGE
#	wifi SHORTCUT [OPTIONS]
#
# ARGUMENTS
#	1. SHORTCUT: Name of wifi shortcut to connect to. Valid values:
#		- home
#		- omega
#		- edu
#		- umass
#		 
#	        scan: If the shortcut is "scan" the script will scan for wifi 
#                     networks.
#
#	        list: If the shortcut is "list" the script will list all the
#                     known wifi networks.
#
#		*:    If the shortcut is any other value the script will try 
#		      connecting to a connman service with the provided 
#		      shortcut value.
#
# OPTIONS
#	--help,-h    Display help text
#
# BEHAVIOR
#	If a shortcut name is specified:     Connects to a wifi network
#	If a wifi command name is specified: Executes the special command
#?
svc=""
case "$1" in
	home)
		svc="wifi_3052cb823a67_4b61746c612d3547_managed_psk"
		;;
	edu)
		svc="wifi_3052cb823a67_656475726f616d_managed_ieee8021x"
		;;
	omega)
		svc="wifi_3052cb823a67_4f6d6567612d30413042_managed_psk"
		;;
	umass)
		svc="wifi_3052cb823a67_554d415353_managed_none"
		;;
	scan)
		echo "scanning"
		connmanctl scan wifi
		exit 0
		;;
	list)
		echo "networks:"
		connmanctl services
		exit 0
		;;
	--help|-h)
		show-help "$0"
		exit 1
		;;
	*)
		svc="$1"
		;;
esac

if [ -z "$svc" ]; then
	echo "Error: service argument must be provided" >&2
	exit 1
fi

echo "connecting to $svc"
connmanctl connect "$svc"
