#!/usr/bin/env bash
#?
# xcopy - Copies stdin to the "normal" clipboard (access with ctrl+{c,v})
#
# USAGE
#	xcopy [OPTIONS] < foo.txt
#	cat foo.txt | xcopy [OPTIONS]
#
# OPTIONS
#	--help,-h    Display help text
#
# BEHAVIOR
#	Sets the clipboard to the contents of stdin.
#?

# Help option
if [[ "$1" =~ ^(--help|-h)$ ]]; then
	show-help "$0"
	exit 1
fi

xclip -selection clipboard
