#!/usr/bin/env bash
#?
# xpaste - Prints the contents of the "normal" clipboard (access with 
#          ctrl+{c,v}) to stdout.
#
# USAGE
#	xpaste [OPTIONS] > foo.txt
#
# OPTIONS
#	--help,-h    Display help text
#
# BEHAVIOR
#	Dumps the contents of the clipboard to stdout.
#?

# Help option
if [[ "$1" =~ ^(--help|-h)$ ]]; then
	show-help "$0"
	exit 1
fi

# Paste
xclip -o -selection clipboard

