#!/usr/bin/env bash
#?
# xrename - Rename X window
#
# USAGE
#
#	xrename [-s,-h] [NAME]
#
# OPTIONS
#
#	-s         Instead of renaming current window, renamed 
#	           window selected by mouse
#	-h         Show help text
#
# ARGUMENTS
#
#    NAME    Name of window. Defaults to current directory name.
#
# BEHAVIOR
#
#	By default renames the window the command was run in.  
#
#	If the -s option is provided renames the window which the user 
#	selects with their mouse.
#
#?

# {{{1 Exit on any error
set -e

# {{{1 Helpers
function die() {
    echo "Error: $@" >&2
    exit 1
}

# {{{1 Options
# {{{2 Get
while getopts "sh" opt; do
    case "$opt" in
	s) select="true" ;;
	h)
	    show-help "$0"
	    exit 1
	    ;;
	'?') die "Unknown option" ;;
    esac
done

shift $((OPTIND-1))

# {{{1 Arguments
name="$1"

if [ -z "$name" ]; then
    name=$(basename $(pwd))
fi

# {{{1 Rename
if [ -z "$select" ]; then # Current window
    if ! xdotool set_window --name "$name" $(xdotool getactivewindow); then
	die "Failed to rename current window"
    fi
else # Select window
    echo "Select window to rename"

    if ! xdotool selectwindow set_window --name "$name"; then
	die "Failed to rename selected window"
    fi
fi

echo "Renamed to $name"
